[project]
name = "spatialhub"
version = "0.1.1"
description = "Pipelines for Spatial Transcriptomics Analysis."
authors = [{ name = "Sansom lab", email = "stephen.sansom@kennedy.ox.ac.uk" }]
dependencies = [
    "snakemake>=9",
    "snakemake-executor-plugin-drmaa",
    "ashlar",
    "pandas==2.3.3",
    "anndata==0.12.16",
    "bin2cell",
    "tensorflow",
    "cell2location",
    "scanpy>=1.12.1",
    "harmonypy",
    "scvi-tools",
    "spatialdata",
    "spatialdata-io",
    "spatialdata-plot",
    "rctd-py",
    "sopa[cellpose]",
    "ipykernel",
    "rich-argparse"
]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project.scripts]
spatialhub = "spatialhub.cli:main"
