[data]
force_2d = true
min_molecules_per_cell = 50
x = "x_global_px"
y = "y_global_px"
z = "z"
gene = "target"
min_molecules_per_gene = 1
min_molecules_per_segment = 12
confidence_nn_id = 26

[segmentation]
scale = -1  # Approximate cell radius, in same value as x/y/z above (for CosMx 400 px ~ 50+ um). Negative values mean it must be estimated from `min_molecules_per_cell`
scale_std = "25%" # cell radius standard deviation
prior_segmentation_confidence = 0.8
estimate_scale_from_centers = true
n_clusters = 6  # Number of clusters (~major cell types) to use for cell type segmentation; increasing this number may enable a larger dynamic range of cell sizes to be considered. Default: 4
iters = 500
n_cells_init = 0
nuclei_genes = ""
cyto_genes = ""

