"""==================
Pipeline segment.py
==================

Overview
--------

This pipeline collates tools for cell segmentation.


Configuration
-------------

The pipeline requires a :file:`pipeline_segment.yml` file.

An example configuration file can be generated by executing:

spatialhub segment config


Inputs
------

(stitched) image


Requirements
------------

The following software is required:

#. python


Output files
------------

The pipeline generates the following outputs:

#. a segmentation mask (compatible with spatialdata)
#. a matching transcripts coordinates file with cell compartment assignment [work in progress]
#. a matching cellxgene count matrix [work in progress]


Code
====

"""

from ruffus import *

import sys
import shutil
import os
from pathlib import Path
import glob

import pandas as pd
import numpy as np

from cgatcore import experiment as E
from cgatcore import pipeline as P
from cgatcore import database as DB
import cgatcore.iotools as IOTools


# import local pipeline utility functions
import spatialhub.tasks as T
import spatialhub.tasks.samples as samples


# ----------------------- < pipeline configuration > ------------------------ #

# Override function to collect config files
P.control.write_config_files = T.write_config_files

# load options from the yml file
P.parameters.HAVE_INITIALIZED = False
PARAMS = P.get_parameters(T.get_parameter_file(__file__))

# set the location of the code directory
PARAMS["spatialhub_code_dir"] = Path(__file__).parents[1]

if len(sys.argv) > 1:
        if(sys.argv[1] == "config") and __name__ == "__main__":
                    sys.exit(P.main(sys.argv))


# ----------------------------- Preflight checks ----------------------------- #

# TBC


# ----------------------- Read in the samples set -------------------------- #

# Only do this when pipeline tasks are being executed.
if len(sys.argv) > 1:
    if sys.argv[1] == "make":
        
        S = samples.samples(sample_tsv = PARAMS["sample_table"])

        #if any([x in ["cosmx"] 
        #        for x in S.technology]): 
        #    runCosMxTasks = True


# ----------------------------- Pipeline tasks ----------------------------- #

def sample_jobs():

    if not os.path.exists("zarr.dir"):
        os.mkdir("zarr.dir")

    if not os.path.exists("segment.dir"):
        os.mkdir("segment.dir")
    
    if not os.path.exists("segment.dir/logs"):
        os.mkdir("segment.dir/logs")

    for sample in S.sample_ids():
        sentinel_file = os.path.join("segment.dir/logs", sample + "_segmentSetup.sentinel")
        yield([None, sentinel_file])


@files(sample_jobs)
def segmentSetup(infile, outfile):
    '''
    Creates 'master' SpatialData object, where all segmentation masks will be registered
    '''

    input_sample = os.path.basename(outfile)[:-len("_segmentSetup.sentinel")]

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["sdata_mem"],
                cpu=1)
    
    statement = '''python %(spatialhub_code_dir)s/python/segment_setup.py
                   --stitchedDir=%(stitched_dir)s
                   --sampleKey=%(input_sample)s
                   --fov2sample=%(sample_table)s
                   --channels=%(channels_dict)s
                   --rmProbes=%(remove_probes)s
                   --probeKey=%(probe_key)s
                   --x=%(x_coord)s
                   --y=%(y_coord)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


############################## Cellpose ##############################

@active_if(PARAMS['run_cellpose'])
@transform(segmentSetup,
           regex(r"(.*)/(.*)_segmentSetup.sentinel"),
           r"\1/\2_patchCellpose.sentinel")
def patchCellpose(infile, outfile):
    '''
    Creates patches for Cellpose segmentation using SOPA (fast implementation)
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["cp_mem"],
                cpu=1)
    
    input_sample = os.path.basename(outfile)[:-len("_patchCellpose.sentinel")]
    slideName = S.samples[input_sample]['slide_id']
    sampleName = S.samples[input_sample]['sample_name']
    
    # SOPA-cellpose parameters
    sample_zarr = os.path.join(f"zarr.dir/{slideName}/", sampleName + ".zarr")
    
    statement = '''sopa patchify image %(sample_zarr)s \
                   --patch-width-pixel %(cp_patch_width)s \
                   --patch-overlap-pixel %(cp_patch_ovlp)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


@transform(patchCellpose,
           regex(r"(.*)/(.*)_patchCellpose.sentinel"),
           r"\1/\2_sopaCellpose_" + PARAMS['cp_model'] + ".sentinel")
def sopaCellpose(infile, outfile):
    '''
    Performs Cellpose segmentation using SOPA (fast implementation)
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["cp_mem"],
                cpu=PARAMS["cp_cpu"])
    
    input_sample = os.path.basename(outfile)[:-len("_sopaCellpose_" + PARAMS['cp_model'] + ".sentinel")]
    slideName = S.samples[input_sample]['slide_id']
    sampleName = S.samples[input_sample]['sample_name']
    
    # SOPA-cellpose parameters
    sample_zarr = os.path.join(f"zarr.dir/{slideName}/", sampleName + ".zarr")

    # Add option to split channel parameter if more than one
    c = str(PARAMS['cp_channels'])
    c = c.replace(",", " --channels ")
    channels = "--channels " + c
    
    statement = '''sopa segmentation cellpose %(sample_zarr)s \
                   %(channels)s \
                   --model-type %(cp_model)s \
                   --diameter %(cp_cell_diameter)s \
                   --min-area %(cp_cell_area)s \
                   --flow-threshold %(cp_flow_thresh)s \
                   --cellprob-threshold %(cp_prob_thresh)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


@transform(sopaCellpose,
           regex(r"(.*)/(.*)_sopaCellpose_" + PARAMS['cp_model'] + ".sentinel"),
           r"\1/\2_sopaCPregister_" + PARAMS['cp_model'] + ".sentinel")
def sopaCPregister(infile, outfile):
    '''
    Registers SOPA cellpose segmentation mask to master spatialdata object, using user key
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["cp_mem"],
                cpu=1)
    
    input_sample = os.path.basename(outfile)[:-len("_sopaCPregister_" + PARAMS['cp_model'] + ".sentinel")]
    slideName = S.samples[input_sample]['slide_id']
    sampleName = S.samples[input_sample]['sample_name']
    
    # SOPA-cellpose parameters
    sample_zarr_old = os.path.join(f"zarr.dir/{slideName}/", sampleName + ".zarr",
                                   "shapes", "cellpose_boundaries")
    sample_zarr_new = os.path.join(f"zarr.dir/{slideName}/", sampleName + ".zarr",
                                   "shapes", PARAMS['cp_mask_key'])
    
    statement = '''mv %(sample_zarr_old)s %(sample_zarr_new)s 
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


############################## Baysor ##############################

#@active_if(PARAMS['run_baysor'])




# --------------------- < generic pipeline tasks > -------------------------- #

@follows(sopaCPregister)
def full():
    pass

print(sys.argv)

def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)

if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
