"""==================
Pipeline sopa_segment_tx.py
==================

Overview
--------

This pipeline adapts the SOPA implementation of Baysor to enable transcripts-based segmentation
of a generic SpatialData object (e.g. as generated via the spatialhub ashlar pipeline).


Configuration
-------------

The pipeline requires a :file:`pipeline_sopa_segment_tx.yml` file.

An example configuration file can be generated by executing:

spatialhub sopa_segment_tx config


Inputs
------

(stitched) transcripts file


Requirements
------------

The following software is required:

#. python


Output files
------------

The pipeline generates the following outputs:

#. a segmentation mask (compatible with spatialdata)


Code
====

"""

from ruffus import *

import sys
import shutil
import os
from pathlib import Path
import glob

import pandas as pd
import numpy as np

from cgatcore import experiment as E
from cgatcore import pipeline as P
from cgatcore import database as DB
import cgatcore.iotools as IOTools


# import local pipeline utility functions
import spatialhub.tasks as T
import spatialhub.tasks.samples as samples


# ----------------------- < pipeline configuration > ------------------------ #

# Override function to collect config files
P.control.write_config_files = T.write_config_files

# load options from the yml file
P.parameters.HAVE_INITIALIZED = False
PARAMS = P.get_parameters(T.get_parameter_file(__file__))

# set the location of the code directory
PARAMS["spatialhub_code_dir"] = Path(__file__).parents[1]

if len(sys.argv) > 1:
        if(sys.argv[1] == "config") and __name__ == "__main__":
                    sys.exit(P.main(sys.argv))


# ----------------------------- Preflight checks ----------------------------- #

# TBC


# ----------------------- Read in the samples set -------------------------- #

# Only do this when pipeline tasks are being executed.
if len(sys.argv) > 1:
    if sys.argv[1] == "make":
        
        S = samples.samples(sample_tsv = PARAMS["sample_table"])

        #if any([x in ["cosmx"] 
        #        for x in S.technology]): 
        #    runCosMxTasks = True


# ----------------------------- Pipeline tasks ----------------------------- #

def sample_jobs():

    if not os.path.exists("sopa.segment.dir"):
        os.mkdir("sopa.segment.dir")
    
    if not os.path.exists("sopa.segment.dir/logs"):
        os.mkdir("sopa.segment.dir/logs")

    for sample in S.sample_ids():
        sentinel_file = os.path.join("sopa.segment.dir/logs", sample + "_sopa_segmentSetup.sentinel")
        yield([None, sentinel_file])


@files(sample_jobs)
def segmentSetup(infile, outfile):
    '''
    Creates 'master' SpatialData object compatible with SOPA
    '''

    input_sample = os.path.basename(outfile)[:-len("_sopa_segmentSetup.sentinel")]

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["sdata_mem"],
                cpu=1)
    
    statement = '''python %(spatialhub_code_dir)s/python/sopa_segment_setup.py
                   --sampleKey=%(input_sample)s
                   --fov2sample=%(sample_table)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


############################## Baysor (using SOPA) ##############################

@active_if(PARAMS['run_baysor'])
@transform(segmentSetup,
           regex(r"(.*)/(.*)_sopa_segmentSetup.sentinel"),
           r"\1/\2_patchBaysor.sentinel")
def patchBaysor(infile, outfile):
    '''
    Creates patches for Baysor segmentation using SOPA (fast implementation)
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["bs_mem"],
                cpu=1)
    
    input_sample = os.path.basename(outfile)[:-len("_patchBaysor.sentinel")]
    slideName = S.samples[input_sample]['slide_id']
    sampleName = S.samples[input_sample]['sample_name']
    
    # SOPA-baysor parameters
    sample_zarr = os.path.join(f"sopa.segment.dir/{slideName}/", sampleName + ".zarr")
    
    statement = '''sopa patchify transcripts %(sample_zarr)s \
                   --patch-width-microns %(bs_patch_width)s \
                   --patch-overlap-microns %(bs_patch_ovlp)s \
                   --prior-shapes-key %(bs_prior_mask)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


@transform(patchBaysor,
           regex(r"(.*)/(.*)_patchBaysor.sentinel"),
           r"\1/\2_sopaBaysor_" + PARAMS['bs_prior_mask'] + ".sentinel")
def sopaBaysor(infile, outfile):
    '''
    Performs Baysor segmentation using SOPA (fast implementation)
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["bs_mem"],
                cpu=PARAMS["bs_cpu"])
    
    input_sample = os.path.basename(outfile)[:-len("_sopaBaysor_" + PARAMS['bs_prior_mask'] + ".sentinel")]
    slideName = S.samples[input_sample]['slide_id']
    sampleName = S.samples[input_sample]['sample_name']
    
    # SOPA-Baysor parameters
    sample_zarr = os.path.join(f"sopa.segment.dir/{slideName}/", sampleName + ".zarr")

    statement = '''module purge; \
                   module load Python/3.10.8 Baysor/0.7.1; \
                   export export SOPA_PARALLELIZATION_BACKEND=thread; \
                   sopa segmentation baysor %(sample_zarr)s \
                       --config '"%(bs_toml)s"' \
                       --min-area %(bs_cell_area)s \
                       &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


@transform(sopaBaysor,
           regex(r"(.*)/(.*)_sopaBaysor_" + PARAMS['bs_prior_mask'] + ".sentinel"),
           r"\1/\2_sopaBSregister_" + PARAMS['bs_prior_mask'] + ".sentinel")
def sopaBSregister(infile, outfile):
    '''
    Registers SOPA Baysor segmentation mask to master spatialdata object, using user key
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["bs_mem"],
                cpu=1)
    
    input_sample = os.path.basename(outfile)[:-len("_sopaBSregister_" + PARAMS['bs_prior_mask'] + ".sentinel")]
    slideName = S.samples[input_sample]['slide_id']
    sampleName = S.samples[input_sample]['sample_name']
    
    # SOPA-Baysor parameters
    sample_zarr_old = os.path.join(f"sopa.segment.dir/{slideName}/", sampleName + ".zarr",
                                   "shapes", "baysor_boundaries")
    sample_zarr_new = os.path.join(f"sopa.segment.dir/{slideName}/", sampleName + ".zarr",
                                   "shapes", PARAMS['bs_mask_key'])
    
    statement = '''mv %(sample_zarr_old)s %(sample_zarr_new)s 
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)




# --------------------- < generic pipeline tasks > -------------------------- #

@follows(sopaBSregister)
def full():
    pass

print(sys.argv)

def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)

if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
