"""==================
Pipeline ashlar.py
==================

Overview
--------

This pipeline creates stitched images for each sample on a slide.


Configuration
-------------

The pipeline requires a :file:`pipeline_ashlar.yml` file.

An example configuration file can be generated by executing:

spatialhub pipeline_ashlar config


Inputs
------

The pipeline assumes the following directory tree structure for your project.

{projDir}
└── {slideName}
    ├── flatFiles
    └── Morphology2D

The pipeline requires the following inputs:

#. A :file:`fov2sample.csv` file per slide in the metadata directory, including a `sample_name` and a `fov_sequence` columns (see see :doc:`Configuration files<configuration.md>` for details)
#. A :directory:`Morphology2D`, listing all FOVs for the corresponding CosMx slide.


Requirements
------------

The following software is required:

#. python
#. R


Output files
------------

The pipeline generates the following outputs:

#. a stitched image per sample
#. a matching transcripts coordinates file with coorected coordinates


Code
====

"""

from ruffus import *

import sys
import shutil
import os
from pathlib import Path
import glob

import pandas as pd
import numpy as np

from cgatcore import experiment as E
from cgatcore import pipeline as P
from cgatcore import database as DB
import cgatcore.iotools as IOTools


# import local pipeline utility functions
import spatialhub.tasks as T
import spatialhub.tasks.samples as samples


# ----------------------- < pipeline configuration > ------------------------ #

# Override function to collect config files
P.control.write_config_files = T.write_config_files

# load options from the yml file
P.parameters.HAVE_INITIALIZED = False
PARAMS = P.get_parameters(T.get_parameter_file(__file__))

# set the location of the code directory
PARAMS["spatialhub_code_dir"] = Path(__file__).parents[1]

if len(sys.argv) > 1:
        if(sys.argv[1] == "config") and __name__ == "__main__":
                    sys.exit(P.main(sys.argv))


# ----------------------------- Preflight checks ----------------------------- #

# TBC


# ----------------------- Read in the samples set -------------------------- #

# Only do this when pipeline tasks are being executed.
if len(sys.argv) > 1:
    if sys.argv[1] == "make":
        
        S = samples.samples(sample_tsv = PARAMS["sample_table"])

        #if any([x in ["cosmx"] 
        #        for x in S.technology]): 
        #    runCosMxTasks = True


# ----------------------------- Pipeline tasks ----------------------------- #

#@active_if(runAshlar)
def slide_jobs():
     
    if not os.path.exists("ashlar.dir"):
        os.mkdir("ashlar.dir")
    
    if not os.path.exists("ashlar.dir/logs"):
        os.mkdir("ashlar.dir/logs")


    for slide in S.slide_ids():
        
        slide_path = os.path.join("ashlar.dir", slide + ".tsv")
        
        # Add if statement to not overwrite date stamp when .tsv file already exists
        if not os.path.isfile(slide_path):
            S.write_tsv("slide_id", slide, slide_path)
            
        sentinel_file = os.path.join("ashlar.dir/logs", slide + ".sentinel")
        
        yield([slide_path, sentinel_file])


@files(slide_jobs)
def splitFlatFiles(infile, outfile):
    '''
    Splits large CosMx flat files by FOV (lower memory requirements)
    '''

    outfile = outfile.replace(".sentinel", "_splitFlatFiles.sentinel")

    t = T.setup(infile, outfile, PARAMS,
                memory=4,
                cpu=1)
    
    input_slide = os.path.basename(infile)[:-len(".tsv")]
    #pattern = "XYZ"  # if wanting to keep original name
    
    # WARNING: cosmx_setup.sh does not work if splitExprMat/splitTxFile directories are not empty.
    # => Add option to check they are empty, or trigger error if directory already exists (?)
    statement = '''%(spatialhub_code_dir)s/bash/cosmx_setup.sh 
                   --directory=%(projDir)s
                   --slide=%(input_slide)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


@files(slide_jobs)
def ashlarSetup(infile, outfile):
    '''
    Copies original FOV files into one separate sub-directory per sample per slide
    '''

    outfile = outfile.replace(".sentinel", "_ashlarSetup.sentinel")

    t = T.setup(infile, outfile, PARAMS,
                memory=4,
                cpu=1)
    
    input_slide = os.path.basename(infile)[:-len(".tsv")]
    
    statement = '''python %(spatialhub_code_dir)s/python/ashlar_setup.py 
                   --projDir=%(projDir)s
                   --slideName=%(input_slide)s
                   --fov2sample=%(sample_table)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


# Now that we've split the dataset per sample, we can operate at this level

def sample_jobs():
    
    for sample in S.sample_ids():
        
        sample_path = os.path.join("ashlar.dir", sample + ".tsv")
        if not os.path.isfile(sample_path):
            S.write_tsv("sample_id", sample, sample_path)
        
        sentinel_file = os.path.join("ashlar.dir/logs", sample + ".sentinel")

        yield([sample_path, sentinel_file])


@follows(sample_jobs, ashlarSetup)
@files(sample_jobs)
def ashlarRename(infile, outfile):
    '''
    Renames FOV files and inserts mock tiles where needed for Ashlar stitching
    '''

    outfile = outfile.replace(".sentinel", "_ashlarRename.sentinel")

    t = T.setup(infile, outfile, PARAMS,
                memory=4,
                cpu=1)
    
    input_sample = os.path.basename(infile)[:-len(".tsv")]
    
    statement = '''python %(spatialhub_code_dir)s/python/ashlar_rename_tiles.py
                   --sampleKey=%(input_sample)s
                   --fov2sample=%(sample_table)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


@follows(sample_jobs, ashlarSetup, ashlarRename)
@files(sample_jobs)
def ashlarStitch(infile, outfile):
    '''
    Stitches FOV files from each sample into one whole microscopy image
    '''

    outfile = outfile.replace(".sentinel", "_ashlarStitch.sentinel")

    t = T.setup(infile, outfile, PARAMS,
                memory=4,
                cpu=1)
    
    input_sample = os.path.basename(infile)[:-len(".tsv")]
    px_size = PARAMS["ashlar_pixel_size"]
    tile_ovlp = PARAMS["ashlar_tile_overlap"]
    keep_channels = PARAMS["ashlar_keep_channels"]
    
    statement = '''python %(spatialhub_code_dir)s/python/ashlar_stitch_cosmx.py 
                   --sampleKey=%(input_sample)s
                   --fov2sample=%(sample_table)s
                   --pxSize=%(px_size)s
                   --tileOvlp=%(tile_ovlp)s
                   --keepChannels=%(keep_channels)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


@follows(sample_jobs, splitFlatFiles, ashlarSetup, ashlarRename, ashlarStitch)
@files(sample_jobs)
def ashlarConvertCoords(infile, outfile):
    '''
    Convert original transcripts coordinates into new coordinate system for each sample
    '''

    outfile = outfile.replace(".sentinel", "_ashlarConvertCoords.sentinel")

    t = T.setup(infile, outfile, PARAMS,
                memory=8,
                cpu=1)
    
    input_sample = os.path.basename(infile)[:-len(".tsv")]
    px_size = PARAMS["ashlar_pixel_size"]
    
    statement = '''Rscript %(spatialhub_code_dir)s/R/ashlar_convert_coords.R
                   --projDir=%(projDir)s
                   --sampleKey=%(input_sample)s
                   --fov2sample=%(sample_table)s
                   --pxSize=%(px_size)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


# --------------------- < generic pipeline tasks > -------------------------- #

@follows(ashlarConvertCoords)
def full():
    pass

print(sys.argv)

def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)

if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
