"""==================
Pipeline roi.py
==================

Overview
--------

This pipeline fetches cell (segment) centroid coordinates for each sample and for a given segmentation mask


Configuration
-------------

The pipeline requires a :file:`pipeline_extractCoords.yml` file.

An example configuration file can be generated by executing:

spatialhub extractCoords config


Inputs
------

SpatialData object with segmentation mask (stored as a `Shapes` object within the .zarr stack)


Requirements
------------

The following software is required:

#. python


Output files
------------

The pipeline generates the following outputs:

#. a list of cell centroid coordinates for the given mask


Code
====

"""

from ruffus import *

import sys
import shutil
import os
from pathlib import Path
import glob

import pandas as pd
import numpy as np

from cgatcore import experiment as E
from cgatcore import pipeline as P
from cgatcore import database as DB
import cgatcore.iotools as IOTools


# import local pipeline utility functions
import spatialhub.tasks as T
import spatialhub.tasks.samples as samples


# ----------------------- < pipeline configuration > ------------------------ #

# Override function to collect config files
P.control.write_config_files = T.write_config_files

# load options from the yml file
P.parameters.HAVE_INITIALIZED = False
PARAMS = P.get_parameters(T.get_parameter_file(__file__))

# set the location of the code directory
PARAMS["spatialhub_code_dir"] = Path(__file__).parents[1]

if len(sys.argv) > 1:
        if(sys.argv[1] == "config") and __name__ == "__main__":
                    sys.exit(P.main(sys.argv))


# ----------------------------- Preflight checks ----------------------------- #

# TBC


# ----------------------- Read in the samples set -------------------------- #

# Only do this when pipeline tasks are being executed.
if len(sys.argv) > 1:
    if sys.argv[1] == "make":
        
        S = samples.samples(sample_tsv = PARAMS["sample_table"])

        #if any([x in ["cosmx"] 
        #        for x in S.technology]): 
        #    runCosMxTasks = True


# ----------------------------- Pipeline tasks ----------------------------- #

def sample_jobs():

    if not os.path.exists("coordinates.dir"):
        os.mkdir("coordinates.dir")
    
    if not os.path.exists("coordinates.dir/logs"):
        os.mkdir("coordinates.dir/logs")
    
    if not os.path.exists("coordinates.dir/" + PARAMS['segmentation_mask']):
        os.mkdir("coordinates.dir/" + PARAMS['segmentation_mask'])
    
    for sample in S.sample_ids():
        sentinel_file = os.path.join("coordinates.dir/logs", sample + "_" + PARAMS['segmentation_mask'] + "_coordsFetch.sentinel")
        yield([None, sentinel_file])


@files(sample_jobs)
#@active_if(PARAMS['preprocessing'])
def coordsFetch(infile, outfile):
    '''
    Fetch centroid coordinates for each cell for a given segementation mask
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["mem"],
                cpu=1)
    
    input_sample = os.path.basename(outfile)[:-len("_" + PARAMS['segmentation_mask'] + "_coordsFetch.sentinel")]

    statement = '''python %(spatialhub_code_dir)s/python/extractCoords_fetch.py
                   --sampleKey=%(input_sample)s
                   --fov2sample=%(sample_table)s
                   --segMask=%(segmentation_mask)s
                   --segIndex=%(segment_index)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)




# --------------------- < generic pipeline tasks > -------------------------- #

@follows(coordsFetch)
def full():
    pass

print(sys.argv)

def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)

if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
