"""==================
Pipeline baysor.py
==================

Overview
--------

This pipeline runs baysor, using a transcripts file annotated with a prior cell mask
(currently only supporting the use of AtoMx default mask as formatted when running spatialhub ashlar;
but the pre-processing step could be skipped and performed manually if starting from another prior)


Configuration
-------------

The pipeline requires a :file:`pipeline_baysor.yml` file.

An example configuration file can be generated by executing:

spatialhub baysor config


Inputs
------

(stitched) image


Requirements
------------

The following software is required:

#. python
#. baysor

# WARNING: baysor/0.7.1 (and earlier) is incompatible with some of the default Sansom Lab modules
# => *before* running this pipeline, but *after* activating your spatial_cgat virtual environment,
# update ~/.bashrc to load only the appropriate version of python and baysor


Output files
------------

The pipeline generates the following outputs:

#. a segmentation mask (compatible with spatialdata)
#. a matching transcripts coordinates file with cell compartment assignment [work in progress]
#. a matching cellxgene count matrix [work in progress]


Code
====

"""

from ruffus import *

import sys
import shutil
import os
from pathlib import Path
import glob

import pandas as pd
import numpy as np

from cgatcore import experiment as E
from cgatcore import pipeline as P
from cgatcore import database as DB
import cgatcore.iotools as IOTools


# import local pipeline utility functions
import spatialhub.tasks as T
import spatialhub.tasks.samples as samples


# ----------------------- < pipeline configuration > ------------------------ #

# Override function to collect config files
P.control.write_config_files = T.write_config_files

# load options from the yml file
P.parameters.HAVE_INITIALIZED = False
PARAMS = P.get_parameters(T.get_parameter_file(__file__))

# set the location of the code directory
PARAMS["spatialhub_code_dir"] = Path(__file__).parents[1]

if len(sys.argv) > 1:
        if(sys.argv[1] == "config") and __name__ == "__main__":
                    sys.exit(P.main(sys.argv))


# ----------------------------- Preflight checks ----------------------------- #

# TBC


# ----------------------- Read in the samples set -------------------------- #

# Only do this when pipeline tasks are being executed.
if len(sys.argv) > 1:
    if sys.argv[1] == "make":
        
        S = samples.samples(sample_tsv = PARAMS["sample_table"])

        #if any([x in ["cosmx"] 
        #        for x in S.technology]): 
        #    runCosMxTasks = True


# ----------------------------- Pipeline tasks ----------------------------- #

def sample_jobs():

    if not os.path.exists("baysor.dir"):
        os.mkdir("baysor.dir")
    
    if not os.path.exists("baysor.dir/logs"):
        os.mkdir("baysor.dir/logs")

    for sample in S.sample_ids():
        sentinel_file = os.path.join("baysor.dir/logs", sample + "_baysorSetup.sentinel")
        yield([None, sentinel_file])


@files(sample_jobs)
#@active_if(PARAMS['preprocessing'])
def baysorSetup(infile, outfile):
    '''
    Pre-processes input Ashlar stitched transcripts file with default AtoMx mask for easy interpretation by Baysor
    '''

    input_sample = os.path.basename(outfile)[:-len("_baysorSetup.sentinel")]

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["sdata_mem"],
                cpu=1)
    
    statement = '''python %(spatialhub_code_dir)s/python/baysor_setup.py
                   --sampleKey=%(input_sample)s
                   --fov2sample=%(sample_table)s
                   --rmProbes=%(remove_probes)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


############################## Baysor ##############################

@transform(baysorSetup,
           regex(r"(.*)/(.*)_baysorSetup.sentinel"),
           r"\1/\2_baysor.sentinel")
def runBaysor(infile, outfile):
    '''
    Performs Baysor segmentation
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["mem"],
                cpu=PARAMS["cpu"])
    
    input_sample = os.path.basename(outfile)[:-len("_baysor.sentinel")]
    slideName = S.samples[input_sample]['slide_id']
    sampleName = S.samples[input_sample]['sample_name']

    # Define output directory for the corresponding sample
    outDir = f"baysor.dir/{slideName}/{sampleName}_baysor"
    if not os.path.exists(outDir):
        os.mkdir(outDir)
    
    # Baysor parameters
    sample_tx = os.path.join(f"baysor.dir/{slideName}/", sampleName + "_stitched_tx.csv")

    # module purge and reload => Necessary workaround as baysor presents
    # some incompatibility with other Sansom Lab/CGAT essential core modules 
    statement = '''module purge; module load Baysor/0.7.1;
                   baysor run %(sample_tx)s :prior \
                   -c %(toml_file)s \
                   --count-matrix-format='tsv' \
                   --output=%(outDir)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


@transform(runBaysor,
           regex(r"(.*)/(.*)_baysor.sentinel"),
           r"\1/\2_baysorFilter.sentinel")
def baysorFilter(infile, outfile):
    '''
    Performs post-processing of Baysor output to remove small cells likely to be artifacts, and adds mask to .zarr stack
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["mem"],
                cpu=1)
    
    input_sample = os.path.basename(outfile)[:-len("_baysorFilter.sentinel")]
    slideName = S.samples[input_sample]['slide_id']
    sampleName = S.samples[input_sample]['sample_name']

    old_baysor_mask = f"zarr.dir/{slideName}/{sampleName}.zarr/shapes/baysor"
    if os.path.exists(old_baysor_mask):
         os.rename(old_baysor_mask, old_baysor_mask + "_old")

    statement = '''python %(spatialhub_code_dir)s/python/baysor_filter.py
                   --sampleKey=%(input_sample)s
                   --fov2sample=%(sample_table)s
                   --minArea=%(min_area)s
                   --minCount=%(min_nCount)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)




# --------------------- < generic pipeline tasks > -------------------------- #

@follows(baysorFilter)
def full():
    pass

print(sys.argv)

def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)

if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
