"""==================
Pipeline ashlar.py
==================

Overview
--------

This pipeline creates stitched images for each sample on a slide.


Configuration
-------------

The pipeline requires a :file:`pipeline_ashlar.yml` file.

An example configuration file can be generated by executing:

spatialhub pipeline_ashlar config


Inputs
------

The pipeline assumes the following directory tree structure for your project.

{projDir}
├── data
│   └── raw
│       └── {slideName}
│           └── Morphology2D
└── metadata
    └── {slideName}_fov2sample.csv

The pipeline requires the following inputs:

#. A :file:`fov2sample.csv` file per slide in the metadata directory, including a `sample_name` and a `fov_sequence` columns (see see :doc:`Configuration files<configuration.md>` for details)
#. A :directory:`Morphology2D`, listing all FOVs for the corresponding CosMx slide.


Requirements
------------

The following software is required:

#. python


Output files
------------

The pipeline generates the following outputs:

#. a data sub-directory, with raw data files re-grouped by sample

{projDir}
├── data
│   ├── grouped
│   │   └── {slideName(s)}
│   │       ├── stitched.dir
│   │       ├── fov2sample.dir
│   │       └── Morphology2D
│   │           └── {sampleName(s)}
│   └── raw
│       └── {slideName(s)}
│           └── Morphology2D
└── metadata
    └── {slideName(s)}_fov2sample.csv

#. a stitched image per sample


Code
====

"""

from ruffus import *

import sys
import shutil
import os
from pathlib import Path
import glob

import pandas as pd
import numpy as np

from cgatcore import experiment as E
from cgatcore import pipeline as P
from cgatcore import database as DB
import cgatcore.iotools as IOTools


# import local pipeline utility functions
import spatialhub.tasks as T
import spatialhub.tasks.samples as samples


# ----------------------- < pipeline configuration > ------------------------ #

# Override function to collect config files
P.control.write_config_files = T.write_config_files

# load options from the yml file
P.parameters.HAVE_INITIALIZED = False
PARAMS = P.get_parameters(T.get_parameter_file(__file__))

# set the location of the code directory
PARAMS["spatialhub_code_dir"] = Path(__file__).parents[1]

if len(sys.argv) > 1:
        if(sys.argv[1] == "config") and __name__ == "__main__":
                    sys.exit(P.main(sys.argv))


# ----------------------------- Preflight checks ----------------------------- #

# TBC


# ----------------------- Read in the samples set -------------------------- #

#runAshlar = False  # This may become handy when expanding pipeline to other technologies where stitching is not required

# Only do this when pipeline tasks are being executed.
if len(sys.argv) > 1:
    if sys.argv[1] == "make":
        
        S = samples.samples(sample_tsv = PARAMS["sample_table"])

        #if any([x in ["cosmx"] 
        #        for x in S.technology]): 
        #    runAshlar = True


# ----------------------------- Pipeline tasks ----------------------------- #

#@active_if(runAshlar)
def slide_jobs():
     
    if not os.path.exists("ashlar.dir"):
        os.mkdir("ashlar.dir")

    for slide in S.slide_ids():
        slide_path = os.path.join("ashlar.dir", slide + ".tsv")
        S.write_tsv("slide_id", slide, slide_path)
        sentinel_file = os.path.join("ashlar.dir", slide + ".sentinel")
        yield([slide_path, sentinel_file])


@files(slide_jobs)
def ashlarSetup(infile, outfile):
    '''
    Copies original FOV files into one separate sub-directory per sample per slide
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=4,
                cpu=1)
    
    input_slide = os.path.basename(infile)[:-len(".tsv")]
    sample_tsv = PARAMS["sample_table"]
    
    statement = '''python %(spatialhub_code_dir)s/python/ashlar_setup.py 
                   --projDir=%(projDir)s
                   --slideName=%(input_slide)s
                   --fov2sample=%(sample_table)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


@follows(slide_jobs, ashlarSetup)
@files(slide_jobs)
def ashlarRename(infile, outfile):
    '''
    Renames FOV files and inserts mock tiles where needed for Ashlar stitching
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=4,
                cpu=1)
    
    input_slide = os.path.basename(infile)[:-len(".tsv")]
    sample_tsv = PARAMS["sample_table"]
    
    statement = '''python %(spatialhub_code_dir)s/python/ashlar_rename_tiles.py 
                   --projDir=%(projDir)s
                   --slideName=%(input_slide)s
                   --fov2sample=%(sample_table)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


# Now we've organised the data directory => Moving on to Ashlar stitching per se

# WARNING: Somehow we need to capture information about the sample name and slide!! 

def sample_jobs():
     
    if not os.path.exists("ashlar.dir"):
        os.mkdir("ashlar.dir")

    for sample in S.sample_ids():
        sample_path = os.path.join("ashlar.dir", sample + ".tsv")
        S.write_tsv("sample_id", sample, sample_path)
        sentinel_file = os.path.join("ashlar.dir", sample + ".sentinel")
        yield([sample_path, sentinel_file])


@follows(sample_jobs, ashlarRename)
@files(sample_jobs)
def ashlarStitch(infile, outfile):
    '''
    Stitches FOV files into one whole microscopy image
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=4,
                cpu=1)
    
    input_sample = os.path.basename(infile)[:-len(".tsv")]
    sample_tsv = PARAMS["sample_table"]
    
    statement = '''python %(spatialhub_code_dir)s/python/ashlar_sitch_cosmx.py 
                   --projDir=%(projDir)s
                   --sampleName=%(input_sample)s
                   --fov2sample=%(sample_table)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


# --------------------- < generic pipeline tasks > -------------------------- #

@follows(ashlarRename)
def full():
    pass

print(sys.argv)

def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)

if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
