"""==================
Pipeline probe QC.py
==================

Overview
--------

This pipeline performs quality control of microscopy slides at the FOV and cell level.


Configuration
-------------

The pipeline requires a :file:`pipeline_probeqc.yml` file.

An example configuration file can be generated by executing:

spatialhub probeqc config


Inputs
------

< TBC >


Requirements
------------

The following software is required:

#. python
#. R


Output files
------------

< TBC >


Code
====

"""

from ruffus import *

import sys
import shutil
import os
from pathlib import Path
import glob

import pandas as pd
import numpy as np

from cgatcore import experiment as E
from cgatcore import pipeline as P
from cgatcore import database as DB
import cgatcore.iotools as IOTools


# import local pipeline utility functions
import spatialhub.tasks as T
import spatialhub.tasks.samples as samples


# ----------------------- < pipeline configuration > ------------------------ #

# Override function to collect config files
P.control.write_config_files = T.write_config_files

# load options from the yml file
P.parameters.HAVE_INITIALIZED = False
PARAMS = P.get_parameters(T.get_parameter_file(__file__))

# set the location of the code directory
PARAMS["spatialhub_code_dir"] = Path(__file__).parents[1]

if len(sys.argv) > 1:
        if(sys.argv[1] == "config") and __name__ == "__main__":
                    sys.exit(P.main(sys.argv))


# ----------------------------- Preflight checks ----------------------------- #

# TBC


# ----------------------------- Pipeline tasks ----------------------------- #

def matrix_jobs():

    if not os.path.exists("probeqc.dir"):
        os.mkdir("probeqc.dir")
    
    if not os.path.exists("probeqc.dir/logs"):
        os.mkdir("probeqc.dir/logs")

    matrix_basename = os.path.splitext(os.path.basename(PARAMS["matrix_file"]))[0]
    sentinel_file = os.path.join("probeqc.dir/logs", matrix_basename + ".sentinel")
    
    yield([None, sentinel_file])


@files(matrix_jobs)
def calculateQCmetrics(infile, outfile):
    '''
    Calculate probe QC metrics
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["mem"],
                cpu=1)
    
    if PARAMS["custom_panel"]:
         customPanel = "--customPanel=" + PARAMS["custom_probes_table"]
    else:
         customPanel = "--customPanel=''"
    
    if PARAMS["FOV_runQC"]:
         runFOVqc = "--runFOVqc=TRUE"
         fovnCountCutoff = "--FOV_nCount_cutoff=" + str(PARAMS["FOV_average_nCount_cutoff"])
         fovSNRCutoff = "--FOV_SNR_cutoff=" + str(PARAMS["FOV_SNR_cutoff"])
    else:
         runFOVqc = "--runFOVqc=FALSE"
         fovnCountCutoff = "--FOV_nCount_cutoff=0"
         fovSNRCutoff = "--FOV_SNR_cutoff=0"
    
    if PARAMS["bruker_runQC"]:
         runBrukerFOVqc = "--runBrukerFOVqc=TRUE"
         brukerCodeFile = "--brukerCodeFile=" + str(PARAMS["bruker_code"])
         brukerDataFile = "--brukerDataFile=" + str(PARAMS["bruker_data"])
    else:
         runBrukerFOVqc = "--runBrukerFOVqc=FALSE"
         brukerCodeFile = "--brukerCodeFile=''"
         brukerDataFile = "--brukerDataFile=''"

    if PARAMS["filtering_sample_remove_failed_FOVs"]:
         rmCellsInFailedFOVs = "--rmCellsInFailedFOVs=TRUE"
    else:
         rmCellsInFailedFOVs = "--rmCellsInFailedFOVs=FALSE"
    
    statement = '''Rscript %(spatialhub_code_dir)s/R/probeqc_calculate_metrics.R 
                   --path2sce=%(matrix_file)s
                   --fov2sample=%(sample_table)s
                   --background=%(probes_background)s
                   --poscontrol=%(probes_poscontrol)s
                   %(customPanel)s
                   %(runFOVqc)s
                   %(fovnCountCutoff)s
                   %(fovSNRCutoff)s
                   %(runBrukerFOVqc)s
                   %(brukerCodeFile)s
                   %(brukerDataFile)s
                   --cell_nCount_cutoff=%(filtering_cell_nCount_cutoff)s
                   --cell_nFeature_cutoff=%(filtering_cell_nFeature_cutoff)s
                   --cell_percentNeg_cutoff=%(filtering_cell_percentNeg_cutoff)s
                   --cell_complexity_cutoff=%(filtering_cell_complexity_cutoff)s
                   --sampleMinCells=%(filtering_sample_min_cells_passQC)s
                   --sampleMinPercent=%(filtering_sample_min_percent_passQC)s
                   %(rmCellsInFailedFOVs)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)




@active_if(PARAMS["compile_reports"] and PARAMS["runFOVqc"])
@transform(calculateQCmetrics,
           regex(r"(.*)/(.*).sentinel"),
           r"\1/\2_reports.sentinel")
def compileFOVreport(infile, outfile):
    '''
    Compile R markdown report for easy lookup of FOV-level QC metrics
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=8,
                cpu=1)

    if not os.path.exists("probeqc.dir/probeqc_header.Rmd"):
        shutil.copy(os.path.join(PARAMS["spatialhub_code_dir"], "reports",
                                 "probeqc_header.Rmd"),
                    "probeqc.dir/probeqc_header.Rmd")

    if not os.path.exists("probeqc.dir/_graphical_params.Rmd"):
        shutil.copy(os.path.join(PARAMS["spatialhub_code_dir"], "reports",
                                 "_graphical_params.Rmd"),
                    "probeqc.dir/_graphical_params.Rmd")
    
    if not os.path.exists("probeqc.dir/probeqc_FOV_report.Rmd"):
        shutil.copy(os.path.join(PARAMS["spatialhub_code_dir"], "reports",
                                 "probeqc_FOV_report.Rmd"),
                    "probeqc.dir/probeqc_FOV_report.Rmd")
    
    statement = ''' Rscript -e 'rmarkdown::render("probeqc.dir/probeqc_FOV_report.Rmd", "html_document")'
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile) 




@active_if(PARAMS["compile_reports"] and PARAMS["runFOVqc"])
@transform(calculateQCmetrics,
           regex(r"(.*)/(.*).sentinel"),
           r"\1/\2_reports.sentinel")
def compileCellReport(infile, outfile):
    '''
    Compile R markdown report for easy lookup of cell-level QC metrics
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=8,
                cpu=1)

    if not os.path.exists("probeqc.dir/probeqc_header.Rmd"):
        shutil.copy(os.path.join(PARAMS["spatialhub_code_dir"], "reports",
                                 "probeqc_header.Rmd"),
                    "probeqc.dir/probeqc_header.Rmd")

    if not os.path.exists("probeqc.dir/_graphical_params.Rmd"):
        shutil.copy(os.path.join(PARAMS["spatialhub_code_dir"], "reports",
                                 "_graphical_params.Rmd"),
                    "probeqc.dir/_graphical_params.Rmd")
    
    if not os.path.exists("probeqc.dir/probeqc_cell_report.Rmd"):
        shutil.copy(os.path.join(PARAMS["spatialhub_code_dir"], "reports",
                                 "probeqc_cell_report.Rmd"),
                    "probeqc.dir/probeqc_cell_report.Rmd")
    
    statement = ''' Rscript -e 'rmarkdown::render("probeqc.dir/probeqc_cell_report.Rmd", "html_document")'
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile) 


# --------------------- < generic pipeline tasks > -------------------------- #

@follows(calculateQCmetrics, compileFOVreport, compileCellReport)
def full():
    pass

print(sys.argv)

def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)

if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
