"""==================
Pipeline muspanPCF.py
==================

Overview
--------

This pipeline uses MuSpAn to calculate a PCF function for every sample in the study.


Configuration
-------------

The pipeline requires a :file:`pipeline_muspanPCF.yml` file.

An example configuration file can be generated by executing:

spatialhub muspanPCF config


Inputs
------

Metadata file of cell type annotations (MuSpAn can also work from SpatialData objects; this needs to be implemented in a future version of this pipeline)


Requirements
------------

The following software is required:

#. python


Output files
------------

The pipeline generates the following outputs:

#. data tables of PCF curve coordinates for every sample


Code
====

"""

from ruffus import *

import sys
import shutil
import os
from pathlib import Path
import glob

import pandas as pd
import numpy as np

from cgatcore import experiment as E
from cgatcore import pipeline as P
from cgatcore import database as DB
import cgatcore.iotools as IOTools


# import local pipeline utility functions
import spatialhub.tasks as T
import spatialhub.tasks.samples as samples


# ----------------------- < pipeline configuration > ------------------------ #

# Override function to collect config files
P.control.write_config_files = T.write_config_files

# load options from the yml file
P.parameters.HAVE_INITIALIZED = False
PARAMS = P.get_parameters(T.get_parameter_file(__file__))

# set the location of the code directory
PARAMS["spatialhub_code_dir"] = Path(__file__).parents[1]

if len(sys.argv) > 1:
        if(sys.argv[1] == "config") and __name__ == "__main__":
                    sys.exit(P.main(sys.argv))


# ----------------------------- Preflight checks ----------------------------- #

# TBC


# ----------------------- Read in the samples set -------------------------- #

# Only do this when pipeline tasks are being executed.
if len(sys.argv) > 1:
    if sys.argv[1] == "make":
        
        S = samples.samples(sample_tsv = PARAMS["sample_table"])

        #if any([x in ["cosmx"] 
        #        for x in S.technology]): 
        #    runCosMxTasks = True


# ----------------------------- Pipeline tasks ----------------------------- #

def sample_jobs():

    if not os.path.exists("muspan.dir"):
        os.mkdir("muspan.dir")
    
    if not os.path.exists("muspan.dir/logs"):
        os.mkdir("muspan.dir/logs")
    
    if not os.path.exists("muspan.dir/" + PARAMS['segmentation_mask']):
        os.mkdir("muspan.dir/" + PARAMS['segmentation_mask'])
    
    if not os.path.exists("muspan.dir/" + PARAMS['segmentation_mask'] + "/PCF"):
        os.mkdir("muspan.dir/" + PARAMS['segmentation_mask'] + "/PCF")

    for sample in S.sample_ids():
        sentinel_file = os.path.join("muspan.dir/logs", sample + "_" + PARAMS['segmentation_mask'] + "_computePCF.sentinel")
        yield([None, sentinel_file])


@files(sample_jobs)
#@active_if(PARAMS['preprocessing'])
def computePCF(infile, outfile):
    '''
    Compute the PCF curve (and optionally, the related Ripley's K statistic) for all pairwise cell types in the dataset
    '''

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS["mem"],
                cpu=1)
    
    input_sample = os.path.basename(outfile)[:-len("_" + PARAMS['segmentation_mask'] + "_computePCF.sentinel")]

    statement = '''python %(spatialhub_code_dir)s/python/muspanPCF_compute.py
                   --sampleKey=%(input_sample)s
                   --fov2sample=%(sample_table)s
                   --segMask=%(segmentation_mask)s
                   --annotFile=%(annotation_file)s
                   --celltypeKey=%(celltype_key)s
                   --minPopSize=%(min_population_size)s
                   --maxR=%(max_radius)s
                   --step=%(annulus_step)s
                   --calcRipK=%(calculate_RipK)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)




# --------------------- < generic pipeline tasks > -------------------------- #

@follows(computePCF)
def full():
    pass

print(sys.argv)

def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)

if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
