import pandas as pd


TASKPARAMS = pd.read_csv(config["run_info_csv"], index_col=0).to_dict(orient="index")
SAMPLES = list(TASKPARAMS.keys())

OUTDIR = config["outdir"]
THREADS = config.get("threads", 8)
MEM_IN_GB = config.get("mem_in_gb", 16)

BIN_SIZE = [2, 8, 16]
CUSTOM_BIN_SIZE = config.get("custom_bin_size", None)
if CUSTOM_BIN_SIZE:
    BIN_SIZE += [CUSTOM_BIN_SIZE]
FMT_BIN_SIZE = [f"{bsize:03}" for bsize in BIN_SIZE]
CUSTOM_BIN_SIZE_CMD = f"--custome-bin-size {CUSTOM_BIN_SIZE}" if CUSTOM_BIN_SIZE else ""


rule target:
    input:
        expand(
            f"{OUTDIR}/{{smp}}/outs/binned_outputs/square_{{fbsize}}um/filtered_feature_bc_matrix.h5",
            smp=SAMPLES,
            fbsize=FMT_BIN_SIZE,
        ),


rule spaceranger_count:
    output:
        expand(
            f"{OUTDIR}/{{smp}}/outs/binned_outputs/square_{{fbsize}}um/filtered_feature_bc_matrix.h5",
            smp=["{smp}"],
            fbsize=FMT_BIN_SIZE,
        ),
    params:
        transcriptome=config["transcriptome"],  # Path of folder containing 10x-compatible reference
        probeset=config.get("probeset", ""),  # Path of probe set CSV.
        slidefiledir=config["slidefiledir"],  # Folder which holds the slide design files, downloaded from 10x Genomics.
        createbam=config.get("createbam", False),  # Enable or disable BAM file generation.
        custbsize_cmd=CUSTOM_BIN_SIZE_CMD,  # Additional bin size alongside the standard ones (2, 8, 16).
        outdir=lambda wc: OUTDIR + "/" + wc.smp,  # Output the results to this directory
        execid=lambda wc: wc.smp,  # A unique run id and output folder name
        fastqdir=lambda wc: TASKPARAMS[wc.smp]["FastqDir"],  # Path to input FASTQ data
        cytaimage=lambda wc: TASKPARAMS[wc.smp]["CytaImage"],  # Brightfield image generated by the CytAssist instrument (the CytAssist image)
        slide=lambda wc: TASKPARAMS[wc.smp]["SlideSerial"],  # Visium slide serial number
        area=lambda wc: TASKPARAMS[wc.smp]["Area"],  # Visium capture area identifier
    threads: THREADS
    resources:
        mem_gb=MEM_IN_GB,
    log:
        f"{OUTDIR}/spaceranger-{{smp}}.log",
    shell:
        """
        cd "{OUTDIR}"
        rmdir "{params.outdir}/outs"
        spaceranger count \
            --id "{params.execid}" \
            --transcriptome "{params.transcriptome}" \
            --probe-set "{params.probeset}" \
            --create-bam "{params.createbam}" \
            --output-dir "{params.outdir}" \
            --fastqs "{params.fastqdir}" \
            --cytaimage "{params.cytaimage}" \
            --slide "{params.slide}" \
            --slidefile "{params.slidefiledir}{params.slide}.vlf" \
            --area "{params.area}" \
            {params.custbsize_cmd}
            > {log} 2>&1
        """
