import pandas as pd


TASKPARAMS = pd.read_csv(config["run_info_csv"], index_col=0).to_dict(orient="index")
SAMPLES = list(TASKPARAMS.keys())

OUTDIR = config["outdir"]
THREADS = config.get("threads", 8)
MEM_IN_GB = config.get("mem_in_gb", 16)


rule target:
    input:
        expand(f"{OUTDIR}/{{smp}}/outs/filtered_feature_bc_matrix.h5", smp=SAMPLES),


rule spaceranger_count:
    output:
        f"{OUTDIR}/{{smp}}/outs/filtered_feature_bc_matrix.h5",
    params:
        transcriptome=config["transcriptome"],  # Path of folder containing 10x-compatible reference
        probeset=config.get("probeset", ""),  # Path of probe set CSV.
        slidefiledir=config["slidefiledir"],  # Folder which holds the slide design files, downloaded from 10x Genomics.
        createbam=config.get("createbam", False),  # Enable or disable BAM file generation.
        outdir=lambda wc: OUTDIR + "/" + wc.smp,  # Output the results to this directory
        execid=lambda wc: wc.smp,  # A unique run id and output folder name
        fastqdir=lambda wc: TASKPARAMS[wc.smp]["FastqDir"],  # Path to input FASTQ data
        cytaimage=lambda wc: TASKPARAMS[wc.smp]["CytaImage"],  # Brightfield image generated by the CytAssist instrument (the CytAssist image)
        slide=lambda wc: TASKPARAMS[wc.smp]["SlideSerial"],  # Visium slide serial number
        area=lambda wc: TASKPARAMS[wc.smp]["Area"],  # Visium capture area identifier
    threads: THREADS
    resources:
        mem_gb=MEM_IN_GB,
    log:
        f"{OUTDIR}/spaceranger-{{smp}}.log",
    shell:
        """
        cd "{OUTDIR}"
        rmdir "{params.outdir}/outs"
        spaceranger count \
            --id "{params.execid}" \
            --transcriptome "{params.transcriptome}" \
            --probe-set "{params.probeset}" \
            --create-bam "{params.createbam}" \
            --output-dir "{params.outdir}" \
            --fastqs "{params.fastqdir}" \
            --cytaimage "{params.cytaimage}" \
            --slide "{params.slide}" \
            --slidefile "{params.slidefiledir}{params.slide}.vlf" \
            --area "{params.area}" \
            > {log} 2>&1
        """
