"""==================
Pipeline scanvi.py
==================

Overview
--------

This pipeline uses scANVI to perform label transfer from a reference dataset.


Configuration
-------------

The pipeline requires a :file:`pipeline_scanvi.yml` file.

An example configuration file can be generated by executing:

spatialhub scanvi config


Inputs
------

#. a reference dataset
#. an AnnData object to be annotated


Requirements
------------

The following software is required:

#. python
#. R


Output files
------------

The pipeline generates the following outputs:

#. cell type annotation metadata


Code
====

"""

from ruffus import *

import sys
import shutil
import os
from pathlib import Path
import glob

import pandas as pd
import numpy as np

from cgatcore import experiment as E
from cgatcore import pipeline as P
from cgatcore import database as DB
import cgatcore.iotools as IOTools


# import local pipeline utility functions
import spatialhub.tasks as T
import spatialhub.tasks.samples as samples


# ----------------------- < pipeline configuration > ------------------------ #

# Override function to collect config files
P.control.write_config_files = T.write_config_files

# load options from the yml file
P.parameters.HAVE_INITIALIZED = False
PARAMS = P.get_parameters(T.get_parameter_file(__file__))

# set the location of the code directory
PARAMS["spatialhub_code_dir"] = Path(__file__).parents[1]

if len(sys.argv) > 1:
        if(sys.argv[1] == "config") and __name__ == "__main__":
                    sys.exit(P.main(sys.argv))


# ----------------------------- Preflight checks ----------------------------- #

# TBC


# ----------------------- Read in the samples set -------------------------- #

# Only do this when pipeline tasks are being executed.
if len(sys.argv) > 1:
    if sys.argv[1] == "make":
        
        #S = samples.samples(sample_tsv = PARAMS["sample_table"])
        A = samples.atlases(atlas_tsv = PARAMS["atlas_table"])
        
        if not os.path.exists("annot.dir"):
            os.mkdir("annot.dir")
    
        if not os.path.exists("annot.dir/logs"):
            os.mkdir("annot.dir/logs")

        if PARAMS["run_scanvi"]:
            if not os.path.exists("annot.dir/scanvi"):
                os.mkdir("annot.dir/scanvi")

        if PARAMS["run_celltypist"]:
            if not os.path.exists("annot.dir/celltypist"):
                os.mkdir("annot.dir/celltypist")
        
        if PARAMS["run_singleR"]:
            if not os.path.exists("annot.dir/singleR"):
                os.mkdir("annot.dir/singleR")


# ----------------------------- Pipeline tasks ----------------------------- #


########### Atlas-level tasks ##########

def ref_jobs():

    for atlas in A.atlas_ids():
        sentinel_file = os.path.join("annot.dir/logs", atlas + "_annotSetup.sentinel")
        yield([None, sentinel_file])


@files(ref_jobs)
def annotSetup(infile, outfile):
    '''
    Takes a reference dataset as input, retrieves Ensembl annotations for provided gene_ids,
    and matches gene_ids to to spatial probe names
    '''

    input_ref = os.path.basename(outfile)[:-len("_annotSetup.sentinel")]

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS['mem_atlas'],
                cpu=1)
    
    if PARAMS["simplify_metadata"]:
         simplifyMetadata = "--reduceMeta=TRUE"
    else:
         simplifyMetadata = "--reduceMeta=FALSE"
    
    statement = '''Rscript %(spatialhub_code_dir)s/R/annot_prepare_reference.R
                    --atlasKey=%(input_ref)s
                    --atlasTSV=%(atlas_table)s
                    %(simplifyMetadata)s
                    --annothubDir=%(annothub_directory)s
                    --path2mapping=%(probes_mapping)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


@transform(annotSetup,
           regex(r"(.*)/(.*)_annotSetup.sentinel"),
           r"\1/\2_subsetReference.sentinel")
def subsetReference(infile, outfile):
    '''
    Train scVI/scANVI model from provided reference
    '''

    input_ref = os.path.basename(outfile)[:-len("_subsetReference.sentinel")]

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS['mem_atlas'],
                cpu=1)
    
    statement = '''python %(spatialhub_code_dir)s/python/annot_subset_reference.py
                    --atlasKey=%(input_ref)s
                    --atlasTSV=%(atlas_table)s
                    --featureSet=%(feature_subset)s
                    --probesMapping=%(probes_mapping)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


@active_if(PARAMS['run_scanvi'])
@transform(subsetReference,
           regex(r"(.*)/(.*)_subsetReference.sentinel"),
           r"\1/\2_scanviTrain.sentinel")
def scanviTrainModel(infile, outfile):
    '''
    Train scVI/scANVI model from provided reference
    '''

    input_ref = os.path.basename(outfile)[:-len("_scanviTrain.sentinel")]

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS['scanvi_mem'],
                cpu=PARAMS['scanvi_cpus'])
    
    scviWorkers = '--scviNumWorkers=' + str(PARAMS['scanvi_cpus'] - 1)
    
    statement = '''python %(spatialhub_code_dir)s/python/annot_scanvi_train.py
                    --atlasKey=%(input_ref)s
                    --atlasTSV=%(atlas_table)s
                    %(scviWorkers)s
                    --scVI_pretrain=%(scanvi_scvi_pretrain)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


########### Atlas x Query-level tasks ##########

def query_jobs():

    for atlas in A.atlas_ids():
        for query in A.query_ids():
            sentinel_file = os.path.join("annot.dir/logs", query + "_mapping-to_" + atlas + ".sentinel")
            yield([None, sentinel_file])


@active_if(PARAMS['scanvi_predict'])
@follows(scanviTrainModel)
@files(query_jobs)
def scanviPredictAnnot(infile, outfile):
    '''
    Predict cell type annotations for a given reference-query pair
    '''

    input_pair = os.path.basename(outfile)[:-len(".sentinel")]
    input_ref = input_pair.split("_mapping-to_")[1]
    input_query = input_pair.split("_mapping-to_")[0]

    t = T.setup(infile, outfile, PARAMS,
                memory=PARAMS['scanvi_mem'],
                cpu=PARAMS['scanvi_cpus'])
    
    scviWorkers = '--scviNumWorkers=' + str(PARAMS['scanvi_cpus'] - 1)
    
    statement = '''python %(spatialhub_code_dir)s/python/annot_scanvi_predict.py
                    --atlasKey=%(input_ref)s
                    --queryKey=%(input_query)s
                    --atlasTSV=%(atlas_table)s
                    %(scviWorkers)s
                   &> %(log_file)s
                ''' % dict(PARAMS, **t.var, **locals())
    
    P.run(statement, **t.resources)
    IOTools.touch_file(outfile)


# < Add task for other cell annotation tools >

#@active_if(PARAMS['run_singleR'])
#@files(query_jobs)

#@active_if(PARAMS['run_celltypist'])
#@files(query_jobs)


# < Add task to harmonize annotations generated from different references/tools >


# --------------------- < generic pipeline tasks > -------------------------- #

@follows(scanviPredictAnnot)
def full():
    pass

print(sys.argv)

def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)

if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
