import os
import pandas as pd
import warnings

tasktab = pd.read_csv(config["spaceranger"]["tasktab"], index_col=0)
assert "CytaImage" in tasktab.columns, "CytaImage column not found in metadata."
assert "FastqDir" in tasktab.columns, "FastqDir column not found in metadata."
assert "SlideSerial" in tasktab.columns, "SlideSerial column not found in metadata."
assert "Area" in tasktab.columns, "Area column not found in metadata."
if "Image" not in tasktab.columns:
    warnings.warn(
        "Microscopy image path not indicated in metadata, running with CytaImage only.",
        UserWarning,
    )
    tasktab["ImageCmd"] = ""
else:
    tasktab["ImageCmd"] = "--image " + tasktab["Image"]
taskdict = tasktab.to_dict(orient="index")
captures = list(taskdict.keys())

binsizes = [2, 8, 16]
custom_bin_size = config["spaceranger"].get("custom_bin_size")
if custom_bin_size:
    binsizes += [custom_bin_size]
    custbsize_cmd = f"--custom-bin-size {custom_bin_size}"
else:
    custbsize_cmd = ""
fmtbinsizes = [f"{bsize:03}" for bsize in binsizes]

probeset = config["spaceranger"].get("probeset")
if probeset:
    probeset_cmd = f"--probe-set {probeset}"
else:
    probeset_cmd = ""

RESOURCES = config.get("resources", {})


rule full:
    input:
        expand(os.path.join(config["outdir"], "zarr.dir", "{cap}.zarr"), cap=captures),
    params:
        sranger_dir=os.path.join(config["outdir"], "spaceranger.dir"),
        zarr_dir=os.path.join(config["outdir"], "zarr.dir"),
    shell:
        """
        chmod -R a-w "{params.sranger_dir}"
        chmod -R a-w "{params.zarr_dir}"
        """


rule spaceranger_count:
    output:
        os.path.join(config["outdir"], "spaceranger.dir", "{cap}/spaceranger.sentinel"),
    log:
        os.path.join(config["outdir"], "spaceranger.dir", "{cap}/spaceranger-{cap}.log"),
    params:
        transcriptome=config["spaceranger"]["transcriptome"],  # Path of folder containing 10x-compatible reference
        probeset_cmd=probeset_cmd,  # Path of probe set CSV.
        slidefiledir=config["spaceranger"]["slidefiledir"],  # Folder which holds the slide design files, downloaded from 10x Genomics.
        createbam=config.get("createbam", False),  # Enable or disable BAM file generation.
        custbsize_cmd=custbsize_cmd,  # Additional bin size alongside the standard ones (2, 8, 16).
        cap="{cap}",  # A unique capture id and output folder name
        fastqdir=lambda wc: taskdict[wc.cap]["FastqDir"],  # Path to input FASTQ data
        cytaimage=lambda wc: taskdict[wc.cap]["CytaImage"],  # Brightfield image generated by the CytAssist instrument (the CytAssist image)
        image_cmd=lambda wc: taskdict[wc.cap]["ImageCmd"],  # Single H&E brightfield image
        slide=lambda wc: taskdict[wc.cap]["SlideSerial"],  # Visium slide serial number
        area=lambda wc: taskdict[wc.cap]["Area"],  # Visium capture area identifier
    resources:
        **RESOURCES,
    shell:
        """
        outdir=$(dirname "{output[0]}")

        spaceranger count \
            --id "{params.cap}" \
            --transcriptome "{params.transcriptome}" \
            {params.probeset_cmd} \
            --create-bam "{params.createbam}" \
            --output-dir "$outdir/{params.cap}" \
            --fastqs "{params.fastqdir}" \
            --cytaimage "{params.cytaimage}" \
            {params.image_cmd} \
            --slide "{params.slide}" \
            --slidefile "{params.slidefiledir}{params.slide}.vlf" \
            --area "{params.area}" \
            {params.custbsize_cmd} \
            > {log} 2>&1

        touch "{output}"
        """


rule make_zarr:
    input:
        rules.spaceranger_count.output,
    output:
        os.path.join(config["outdir"], "zarr.dir", "{cap}.zarr"),
    log:
        os.path.join(config["outdir"], "zarr.dir", "mkzarr-{cap}.log"),
    params:
        outdir=os.path.join(config["outdir"], "zarr.dir"),
        cap="{cap}",
        use_filtered=config["make_zarr"].get("use_filtered", True),
    resources:
        **RESOURCES,
    run:
        import warnings
        import spatialdata_io as spdio

        from contextlib import redirect_stdout, redirect_stderr

        with open(log[0], "w") as log_file:
            with redirect_stdout(log_file), redirect_stderr(log_file):
                with warnings.catch_warnings():
                    warnings.filterwarnings(
                        "ignore",
                        category=UserWarning,
                        message=".*Variable names are not unique.*",
                    )

                    sdata = spdio.visium_hd(
                        path=os.path.dirname(input[0]),
                        dataset_id=params.cap,
                        filtered_counts_file=params.use_filtered,
                        load_segmentations_only=False,
                        load_nucleus_segmentations=True,
                        bins_as_squares=True,
                        annotate_table_by_labels=True,
                        fullres_image_file=taskdict[params.cap].get("Image"),
                        load_all_images=True,
                        var_names_make_unique=True,
                    )

                sdata.write(os.path.join(params.outdir, f"{params.cap}.zarr"))
