import os
import pandas as pd


TASKS = pd.read_csv(config["metadata"], index_col=0).to_dict(orient="index")
TASK_IDS = list(TASKS.keys())

OUTDIR = config["outdir"]
THREADS = config.get("threads", 8)
MEM_IN_GB = config.get("mem_in_gb", 16)

BIN_SIZE = [2, 8, 16]
CUSTOM_BIN_SIZE = config.get("custom_bin_size", None)
if CUSTOM_BIN_SIZE:
    BIN_SIZE += [CUSTOM_BIN_SIZE]
FMT_BIN_SIZE = [f"{bsize:03}" for bsize in BIN_SIZE]
CUSTOM_BIN_SIZE_CMD = f"--custome-bin-size {CUSTOM_BIN_SIZE}" if CUSTOM_BIN_SIZE else ""


def IMAGE_CMD(task_id):
    return f"--image {TASKS[task_id]['Image']}" if TASKS[task_id]["Image"] else ""


rule target:
    input:
        expand(
            os.path.join(
                OUTDIR,
                "{id}/outs/binned_outputs/square_{fbsize}um/filtered_feature_bc_matrix.h5",
            ),
            id=TASK_IDS,
            fbsize=FMT_BIN_SIZE,
        ),


rule spaceranger_count:
    output:
        expand(
            os.path.join(
                OUTDIR,
                "{id}/outs/binned_outputs/square_{fbsize}um/filtered_feature_bc_matrix.h5",
            ),
            id=["{id}"],
            fbsize=FMT_BIN_SIZE,
        ),
    params:
        transcriptome=config["transcriptome"],  # Path of folder containing 10x-compatible reference
        probeset=config.get("probeset", ""),  # Path of probe set CSV.
        slidefiledir=config["slidefiledir"],  # Folder which holds the slide design files, downloaded from 10x Genomics.
        createbam=config.get("createbam", False),  # Enable or disable BAM file generation.
        custbsize_cmd=CUSTOM_BIN_SIZE_CMD,  # Additional bin size alongside the standard ones (2, 8, 16).
        execid="{id}",  # A unique run id and output folder name
        outdir=os.path.join(OUTDIR, "{id}"),  # Output the results to this directory
        fastqdir=lambda wc: TASKS[wc.id]["FastqDir"],  # Path to input FASTQ data
        cytaimage=lambda wc: TASKS[wc.id]["CytaImage"],  # Brightfield image generated by the CytAssist instrument (the CytAssist image)
        image_cmd=lambda wc: IMAGE_CMD(wc.id),  # Single H&E brightfield image
        slide=lambda wc: TASKS[wc.id]["SlideSerial"],  # Visium slide serial number
        area=lambda wc: TASKS[wc.id]["Area"],  # Visium capture area identifier
        bsizelststr=" ".join(FMT_BIN_SIZE),  # used to delete automatically generated output folders, to avoid spaceranger not pipestance error
    threads: THREADS
    resources:
        mem_gb=MEM_IN_GB,
    log:
        os.path.join(OUTDIR, "spaceranger-{id}.log"),
    shell:
        """
        cd "{OUTDIR}"
        for r in {params.bsizelststr}; do
            rmdir "{params.execid}/outs/binned_outputs/square_"$r"um"
        done
        rmdir -p "{params.execid}/outs/binned_outputs/"
        spaceranger count \
            --id "{params.execid}" \
            --transcriptome "{params.transcriptome}" \
            --probe-set "{params.probeset}" \
            --create-bam "{params.createbam}" \
            --output-dir "{params.outdir}" \
            --fastqs "{params.fastqdir}" \
            --cytaimage "{params.cytaimage}" \
            {params.image_cmd} \
            --slide "{params.slide}" \
            --slidefile "{params.slidefiledir}{params.slide}.vlf" \
            --area "{params.area}" \
            {params.custbsize_cmd} \
            > {log} 2>&1
        """
