"""
Run Ashlar on a set of full-grid tiles generated by `cosmx_organiseFields.py`.

Outputs
-------
- A stitched OME-TIFF file of the field tiles.
- A CSV file with the positions and shifts of the field tiles.

This script is adapted from https://gist.github.com/jmuhlich/59e114243278cf27e7f0720c2c956484.
"""

import os
import numpy as np
import pandas as pd

from argparse import ArgumentParser as AP
from ashlar.fileseries import FileSeriesReader
from ashlar.reg import EdgeAligner, Mosaic, PyramidWriter
from spatialhub.scripts.utils import GREEN, RESET, print_arguments, die


def main():
    p = AP(description="Run Ashlar on CosMx FOV tiles.")
    p.add_argument("--out-pfx", required=True, help="Prefix for the output files.")
    p.add_argument("--gridpos-csv", required=True, help="Grid position CSV file.")
    p.add_argument("--field-dir", required=True, help="Field directory for stitching.")
    p.add_argument("--name-pattern", required=True, help="Pattern for FOV filenames.")
    p.add_argument("--px-size", type=float, default=0.120280945, help="Pixel size.")
    p.add_argument("--overlap", type=float, default=0.01, help="FOV overlap fraction.")
    p.add_argument("--ch-align", type=int, default=0, help="Channel for alignment.")
    p.add_argument("--ch-out", default=None, help="Comma-separated channels to output.")
    args = p.parse_args()
    print_arguments(args)

    out_csv = f"{args.out_pfx}_stitched.positions.csv"
    out_tiff = f"{args.out_pfx}_stitched.ome.tiff"
    if os.path.exists(out_csv) or os.path.exists(out_tiff):
        raise FileExistsError(f"Output file '{out_csv}' or '{out_tiff}' already exists")

    if not os.path.exists(args.gridpos_csv):
        raise FileNotFoundError(f"Grid position file '{args.gridpos_csv}' not found")
    gridpos = pd.read_csv(args.gridpos_csv)

    # Validate grid index column and uniqueness
    if "grid_index" not in gridpos.columns:
        raise ValueError("'grid_index' column is required in grid position CSV")
    gridpos.set_index("grid_index", inplace=True)
    if not gridpos.index.is_unique:
        raise ValueError("Duplicate grid_index detected")

    # Validate required FOV, col_index, and row_index columns
    if "FOV" not in gridpos.columns:
        raise ValueError("'FOV' column is required in grid position CSV")
    if "col_index" not in gridpos.columns:
        raise ValueError("'col_index' column is required in grid position CSV")
    if "row_index" not in gridpos.columns:
        raise ValueError("'row_index' column is required in grid position CSV")

    # Validate directory for field symbolic links
    if not os.path.isdir(args.field_dir):
        raise FileNotFoundError(f"field directory '{args.field_dir}' does not exist")

    # Parse channels to write
    ch_lst = list(map(int, args.ch_out.split(","))) if args.ch_out is not None else None

    # Determine grid dimensions
    ncols, nrows = gridpos["col_index"].max() + 1, gridpos["row_index"].max() + 1
    print(f"Parsed grid dimensions: {ncols} columns x {nrows} rows.")
    grid2fov = gridpos["FOV"].to_dict()

    # Read the field tiles using FileSeriesReader
    reader = FileSeriesReader(
        args.field_dir,
        pattern=args.name_pattern,
        width=ncols,
        height=nrows,
        overlap=args.overlap,
        pixel_size=args.px_size,
    )
    nfiles, ngrids = reader.metadata.num_images, len(grid2fov)
    if nfiles != ngrids:
        raise ValueError(f"field number mismatch: {nfiles} files but {ngrids} rows")

    # Align the field tiles using EdgeAligner
    aligner = EdgeAligner(reader, channel=args.ch_align)
    aligner.run()

    # Write out the stitched mosaic to an OME-TIFF file
    mosaic = Mosaic(aligner, aligner.mosaic_shape, channels=ch_lst)
    writer = PyramidWriter([mosaic], out_tiff)
    writer.run()
    print(f"Wrote output to '{out_tiff}'.")

    # Write out the positions and shifts to a CSV file
    coords_df = pd.DataFrame(
        np.hstack([aligner.positions, aligner.shifts]),
        columns=["Position_Y", "Position_X", "Shift_Y", "Shift_X"],
        index=pd.Series([s for _, s in reader.metadata.all_series], name="grid_index"),
    ).round(5)
    coords_df["FOV"] = coords_df.index.map(grid2fov)
    coords_df.to_csv(out_csv, index_label="grid_index")
    print(f"Wrote output to '{out_csv}'.")

    print(f"{GREEN}Ashlar completed successfully.{RESET}")


if __name__ == "__main__":
    try:
        main()
    except Exception:
        die("Failed to run Ashlar.")
