#!/usr/bin/env python3

import os
import sys
import argparse
import pandas as pd


### PARAMETERS ###

print("Parsing arguments")
parser = argparse.ArgumentParser()

parser.add_argument("--sampleKey", default="None", type=str,
                    help="unique sample_id as in samples.tsv file, referring to the sample to execute the script on")
parser.add_argument("--fov2sample", default="samples.tsv", type=str,
                    help="path to the spatialhub samples TSV table")
parser.add_argument("--rmProbes", default="Neg,Sys,Bac", type=str,
                    help="patterns of probes to exclude from main transcripts table")

args = parser.parse_args()


### SETUP ###

# Read in metadata file
path2meta = f"{args.fov2sample}"
df = pd.read_csv(path2meta, sep = "\t")

if "sample_name" not in df.columns:
    print("'sample_name' not found: setting it to 'sample_id'")
    df["sample_name"] = df["sample_id"]

# Subset to sample of interest
df = df[df["sample_id"] == args.sampleKey]
assert df.shape[0] == 1, "sample data frame can only have one single row"
df.index = [0]
print(df)
slideName = list(set(df["slide_id"]))[0]
sampleName = list(set(df["sample_name"]))[0]
print("Pre-processing stitched trasncripts file for sample:", sampleName, slideName)


# Define paths to source and destination directories for corresponding sample
path2tx = f"ashlar.dir/{slideName}/Stitched2D/{sampleName}_stitched_tx.csv"  # this is generated by the ashlar pipeline
assert os.path.exists(path2tx), "Sample stitched transcripts file does not exist. Please run `spatialhub ashlar` first."

outDir = f"baysor.dir/{slideName}/"
os.makedirs(outDir, exist_ok=True)


# Parse probes to exclude
x = str(args.rmProbes)
rm_probes_regex = x.replace(",", "|")
print("Using the following regex pattern for probes to exclude:", rm_probes_regex)


#### TASKS ###

# Import stitched transcripts file
df = pd.read_csv(path2tx)

# Reformat variable containing prior segmentation information to integer,
# with all unassigned transcripts assigned the value '0'

print('Adding `prior` variable to data table')
df['prior'] = df['atomx_index'].astype(str)
df['prior'] = df['prior'].str.replace('FOV', '')
df['prior'] = df['prior'].str.replace('_C', '')

print('Re-encoding unassigned transcripts as 0')
nanMask = df['atomx_CellComp'].isnull()
df.loc[nanMask, 'prior'] = '0'
df['prior'] = df['prior'].astype(int)

print(df)


# Exclude negative and system control probes

print('Removing negative and system control probes from transcripts file')
delIdx = df['target'].str.contains('Negative|System|Blank')
df = df[~delIdx]

if rm_probes_regex != 'none':
    print('Removing user-defined probes from transcripts file')
    delIdx = df['target'].str.contains(rm_probes_regex)
    df = df[~delIdx]


# Save!
print("Saving pre-processed transcripts file")
df.to_csv(os.path.join(outDir, f'{sampleName}_stitched_tx.csv'))