#!/usr/bin/env python3

#import sopa  # Note: spatialdata incompatible with latest dask, hence 'Future Warning'

import os
import sys
import argparse
import pandas as pd
import spatialdata as sd
from spatialdata import models
import sopa


### PARAMETERS ###

print("Parsing arguments")
parser = argparse.ArgumentParser()

#parser.add_argument("--stitchedDir", default="./ashlar.dir", type=str,
#                    help="path to the project directory containing stitched data")
parser.add_argument("--sampleKey", default="None", type=str,
                    help="unique sample_id as in samples.tsv file, referring to the sample to execute the script on")
parser.add_argument("--fov2sample", default="samples.tsv", type=str,
                    help="path to the spatialhub samples TSV table")
#parser.add_argument("--channels", default="PanCK,CD68,Membrane,CD45,DNA", type=str,
#                    help="channel dictionary")
#parser.add_argument("--rmProbes", default="Neg,Sys,Bac", type=str,
#                    help="patterns of probes to exclude from main transcripts table")
#parser.add_argument("--probeKey", default="target", type=str,
#                    help="name of variable listing probes in transcripts file (e.g. target or gene)")
#parser.add_argument("--x", default="x_global_px", type=str,
#                    help="names of X spatial coordinate in transcript file")
#parser.add_argument("--y", default="y_global_px", type=str,
#                    help="names of Y spatial coordinate in transcript file")

args = parser.parse_args()


### SETUP ###

# Read in metadata file
path2meta = f"{args.fov2sample}"
df = pd.read_csv(path2meta, sep = "\t")

if "sample_name" not in df.columns:
    print("'sample_name' not found: setting it to 'sample_id'")
    df["sample_name"] = df["sample_id"]

# Subset to sample of interest
df = df[df["sample_id"] == args.sampleKey]
assert df.shape[0] == 1, "sample data frame can only have one single row"
df.index = [0]
print(df)
slideName = list(set(df["slide_id"]))[0]
sampleName = list(set(df["sample_name"]))[0]
print("Creating SOPA-compatible spatial data object for sample:", sampleName, slideName)


# Define paths to source and destination directories for corresponding sample
zarrDir = f"zarr.dir/{slideName}/"  # this is generated by the ashlar pipeline
path2zarr = os.path.join(zarrDir, sampleName + ".zarr")
assert os.path.exists(path2zarr), "Please generate a SpatialData object at the following path:" + path2zarr + "(e.g. using `spatialhub ashlar`)"

sopaDir = f"sopa.segment.dir/{slideName}/"
os.makedirs(sopaDir, exist_ok=True)

outFile = os.path.join(sopaDir, sampleName + ".zarr")
if os.path.exists(outFile):
    print(outFile + " already exists - exiting .zarr creation script.")
    sys.exit()  # Terminate the script with status code 0


#### TASKS ###

# Fetch necessary elements from master SpatialData object
print("Sourcing pre-existing SpatialData object:")
sdata = sd.read_zarr(path2zarr)
print(sdata)

# Subsetting sdata object to one single transcripts table, and renaming it as expected by default in SOPA
print("Subsetting sdata to its minimal elements, as expected by SOPA")

if 'atomx' in sdata.shapes.keys():
    sdata = sdata.subset(['image', 'atomx', 'tx_main'])
else:
    sdata = sdata.subset(['image', 'tx_main'])

sdata['transcripts'] = sdata['tx_main']
del sdata['tx_main']
print(sdata)

print("Saving SOPA-compatible .zarr file")
sdata.write(outFile, overwrite=True)
